name: SPBM checks
run-name: Checks on ${{ github.ref_name }}
on: [push]

permissions:
  contents: read

jobs:
  checks:
    name: Check basic usage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pandoc
        run: sudo apt install -y pandoc
      - name: Prepare asserting script
        run: |
          echo 'import os' > ls_assert.py
          echo 'import sys' >> ls_assert.py
          echo 'contents = {"ls_assert.py"}' >> ls_assert.py
          echo 'contents |= {".git", ".github", ".gitignore"}' >> ls_assert.py
          echo 'contents |= {"README.md", "LICENCE", "Makefile"}' >> ls_assert.py
          echo 'assert set(os.listdir()) == contents | set(sys.argv[1:])' >> ls_assert.py
      - name: Assert empty
        run: python3 ls_assert.py
      - name: Run `make init`
        run: make init TITLE=test-title
      - name: Assert initialized
        run: python3 ls_assert.py source media
      - name: Run `make`
        run: make
      - name: Assert built
        run: python3 ls_assert.py source media build .sections .templates
      - name: Run `make clean`
        run: make clean
      - name: Assert cleaned
        run: python3 ls_assert.py source media
